### ISSUE TITLE
Dying with a Dio's Best Friend on MP gives an extra one.

### ISSUE THREAD

**Issue by DiogoAndreBotas** [NotTsunami/ArtifactOfOrder#1]
Was playing with some friends and one of them got sequenced and received an extra Dio's. Pretty sure it was your mod! :)

**Comment by NotTsunami** [comment]
Should be fixed by https://github.com/NotTsunami/SequenceOnDeath/commit/4366f8885a57245c7658ead3548336128389cdde, version 1.1.0 going up on Thunderstore now
